version: '3.8'
services:
  airflow-webserver:
    image: apache/airflow:2.1.0
    command: webserver
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:hello@host.docker.internal:5434/traffic_data
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - PYTHONPATH=/opt/airflow/dags:/opt/airflow/utils:$PYTHONPATH
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./utils:/opt/airflow/utils
      - ./data:/opt/airflow/data

  airflow-scheduler:
    image: apache/airflow:2.1.0
    command: scheduler
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:hello@host.docker.internal:5434/traffic_data
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - PYTHONPATH=/opt/airflow/dags:/opt/airflow/utils:$PYTHONPATH
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./utils:/opt/airflow/utils
      - ./data:/opt/airflow/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  redash:
    image: redash/redash
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      REDASH_DATABASE_URL: postgresql+psycopg2://postgres:hello@localhost:5434/traffic_data
    volumes:
      - redash-data:/opt/redash

  server:
    image: redash/redash:10.0.0-b50363
    command: server
    depends_on:
      - redis
    ports:
      - "5000:5000"  # Redash web interface
    environment:
      REDASH_WEB_WORKERS: 4
      REDASH_LOG_LEVEL: "INFO"
      PYTHONUNBUFFERED: 0
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres:hello@host.docker.internal:5434/redash"
      REDASH_COOKIE_SECRET: veryverysecret
  scheduler:
    image: redash/redash:10.0.0-b50363
    command: scheduler
    depends_on:
      - server
      - redis
    environment:
      REDASH_LOG_LEVEL: "INFO"
      PYTHONUNBUFFERED: 0
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres:hello@host.docker.internal:5434/redash"
      QUEUES: "celery"
      WORKERS_COUNT: 1
  worker:
    image: redash/redash:10.0.0-b50363
    command: worker
    depends_on:
      - server
      - redis
    environment:
      REDASH_LOG_LEVEL: "INFO"
      PYTHONUNBUFFERED: 0
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres:hello@host.docker.internal:5434/redash"
      QUEUES: "*"
      WORKERS_COUNT: 2

volumes:
  redash-data:
