version: '3.8'
services:
  airflow-webserver:
    image: apache/airflow:2.1.0
    command: webserver
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:hello@host.docker.internal:5434/traffic_data
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  airflow-scheduler:
    image: apache/airflow:2.1.0
    command: scheduler
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:hello@host.docker.internal:5434/traffic_data
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  dbt:
    image: ghcr.io/dbt-labs/dbt-core:1.7.13
    environment:
      DBT_PROFILES_DIR: /usr/app/profiles
    volumes:
      - ./dbt:/usr/app

  redash:
    image: redash/redash
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      REDASH_DATABASE_URL: postgresql+psycopg2://postgres:hello@localhost:5434/traffic_data
    volumes:
      - redash-data:/opt/redash

volumes:
  redash-data:
