version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.1.0
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://dbuser:dbpassword@postgres/dbname
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  dbt:
    image: ghcr.io/dbt-labs/dbt-core:1.7.13
    environment:
      DBT_PROFILES_DIR: /usr/app/profiles
    volumes:
      - ./dbt:/usr/app
    depends_on:
      - postgres

  redash:
    image: redash/redash
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      REDASH_DATABASE_URL: postgresql://dbuser:dbpassword@postgres/dbname
    volumes:
      - redash-data:/opt/redash

volumes:
  postgres-data:
  redash-data: