traffic_dbt:
  outputs:
    dev:
      dbname: traffic_data_dbt
      host: localhost
      pass: hello
      port: 5434
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev